# Gradle
org.gradle.jvmargs=-Xmx2G -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8
org.gradle.caching=true
org.gradle.configureondemand=true
org.gradle.configuration-cache=true
# Loom
fabric.loom.multiProjectOptimisation=true
# Mod Metadata
group=io.github.CrazedTinkerer
user=CrazedTinkerer
slug=crazy-pogo
modId=crazy_pogo
modName=Crazy Pogo!
modDescription=Adds a pogo stick that lets you bounce off of surfaces.
authors=Talinkri
contributors=
license=MIT
# Mod Version
modVersion=0.2.2
# Branch Metadata
branchName=fabric-1.21.8
compatibleVersions=1.21.8
compatibleLoaders=fabric
